# Generated by Django 3.1.3 on 2020-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWB', models.IntegerField()),
                ('sfname', models.CharField(max_length=20)),
                ('slname', models.CharField(max_length=20)),
                ('streetadd', models.CharField(max_length=30)),
                ('streetadd2', models.CharField(max_length=30)),
                ('scity', models.CharField(max_length=20)),
                ('sstate', models.CharField(max_length=20)),
                ('scountry', models.CharField(max_length=20)),
                ('spostal', models.IntegerField()),
                ('smobile', models.IntegerField()),
                ('Rfname', models.CharField(max_length=20)),
                ('Rlname', models.CharField(max_length=20)),
                ('Rstreetadd', models.CharField(max_length=30)),
                ('Rstreetadd2', models.CharField(max_length=30)),
                ('Rcity', models.CharField(max_length=20)),
                ('Rstate', models.CharField(max_length=20)),
                ('Rcountry', models.CharField(max_length=20)),
                ('Rpostal', models.IntegerField()),
                ('Rmobile', models.IntegerField()),
                ('weight', models.FloatField()),
                ('shiptype', models.CharField(choices=[('type', 'TYPE'), ('parcel', 'PARCEL'), ('document', 'DOCUMENT')], default='type', max_length=10)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
